### PR TITLE
split check for headers and library, fix #2

### LINKED ISSUE #2: Change in config9.m4 break build
Please revert to config9.m4 from 0.5.5

Change results to (PD_DIR=/usr/include)

	PHP_ADD_LIBRARY_WITH_PATH(pq, $PQ_DIR/$PHP_LIBDIR, PQ_SHARED_LIBADD)

Which add an invalid rpath.

    ERROR   0002: file '/usr/lib64/php-zts/modules/pq.so' contains an invalid rpath '/usr/include/lib' in [/usr/include/lib]
    ERROR   0002: file '/usr/lib64/php/modules/pq.so' contains an invalid rpath '/usr/include/lib' in [/usr/include/lib]

### PR DESCRIPTION
**Pull request by remicollet**
This should fix issue #2 and keep compatibility for debian.

### CODE REVIEW

**Comment by remicollet** [comment]
Perhaps using pkg-config output could be an even better way...

**Comment by remicollet** [comment]
Thanks for merging and for the rights.

**Comment by m6w6** [comment]
You're welcome!

Hm... travis-ci seems to be unable to find libpq now

**Comment by remicollet** [comment]
Where is located libpq.so on this distro ?

**Comment by remicollet** [comment]
Ok... /usr/lib/x86_64-linux-gnu/libpq.so

**Comment by remicollet** [comment]
I think 5b7491863d7987e4d2d24d4071f93a0aa32c9b07 is the right way to go

(old code kept, but only used when pg_config not available or when DIR is given)

**Comment by m6w6** [comment]
Tahnk you, Remi!

**Pull request merged**
