### PR TITLE
Mark properties as read-only when no write method

### PR DESCRIPTION
**Pull request by remicollet**
Supported by PHP 8.1+
no change  for older versions

### CODE REVIEW

**Comment by m6w6** [comment]
Hmm, after a quick thought, I'm skeptical that a lot of those properties actually adhere to PHP's `readonly` semantics, but are rather `private::set`, which doesn't exist in PHP...

**Comment by m6w6** [comment]
Meaning: lots of them, may change the value during lifetime...

**Comment by remicollet** [comment]
Please check for "socket" property which use std handler, so can probably be changed...

**Comment by remicollet** [comment]
> Meaning: lots of them, may change the value during lifetime...

Hmmm
I understand read-only, as cannot be set by user, not as immutable...

**Comment by m6w6** [comment]
Yeah, that's what extension authors usually "declared" `readonly`, but if `ZEND_ACC_READONLY` resembles [userland `readonly`](https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.readonly-properties), it means something totally different, doesn't it?

> A readonly property can only be initialized once, and only from the scope where it has been declared. Any other assignment or modification of the property will result in an [Error](https://www.php.net/manual/en/class.error.php) exception.

**Comment by remicollet** [comment]
Following code is very confusing
```
$con = new pq\Connection(PQ_DSN);
var_dump($con->status);
var_dump($con->status = 125);
var_dump($con->status);
```

Output:
```
int(0)
int(125)
int(0)
```

And strangely `ZEND_ACC_READONLY` change nothing (we may expect some error/exception)

**Comment by remicollet** [comment]
> Yeah, that's what extension authors usually "declared" `readonly`, but if `ZEND_ACC_READONLY` resembles [userland `readonly`](https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.readonly-properties), it means something totally different, doesn't it?
> 
> > A readonly property can only be initialized once, and only from the scope where it has been declared. Any other assignment or modification of the property will result in an [Error](https://www.php.net/manual/en/class.error.php) exception.

https://wiki.php.net/rfc/readonly_properties_v2 also says

**Comment by remicollet** [comment]
Understood, readonly only apply to typed property, so have to 
 
```
-       zend_declare_property_long(php_pqconn_class_entry, ZEND_STRL("status"), CONNECTION_BAD, ZEND_ACC_PUBLIC|ZEND_ACC_READONLY);
+       zval status_default_value;
+       ZVAL_UNDEF(&status_default_value);
+       zend_string *status_column_name = zend_string_init("status", sizeof("status") - 1, 1);
+       zend_declare_typed_property(php_pqconn_class_entry, status_column_name, &status_default_value, ZEND_ACC_PUBLIC|ZEND_ACC_READONLY, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
```
And then

```
Fatal error: Uncaught Error: Cannot initialize readonly property pq\Connection::$status from global scope in /work/GIT/pecl-and-ext/pq/prop.php:12
```

Else the readonly attribute is only for documentation (reflection)

**Comment by m6w6** [comment]
> Objects (or resources) stored in readonly properties may still be modified internally

^^^^^ Read that again ;-) **objects** and **resources** (i.e. objects containing other properties, or e.g. file contents of underlying resources)

**Comment by remicollet** [comment]
OK, so we don't have same idea ;)

**Pull request closed without merging**
